# Generated by Django 5.0.2 on 2025-09-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_user',
            name='re_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
