# Generated by Django 5.0.2 on 2025-09-26 00:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0005_interface_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interface_user',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
