# Generated by Django 5.2.1 on 2025-05-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="register_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("confirm_password", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("confirm_email", models.EmailField(max_length=254)),
                (
                    "dept",
                    models.CharField(
                        choices=[
                            ("Admin", "Administrator"),
                            ("CAO", "Baş Analiz Sorumlusu veya Baş İdari Sorumlu"),
                            ("MD", "Genel Müdür"),
                            ("SUPR", "Süpervizör"),
                            ("UX", "User Experience"),
                            ("IX", "Interface Experience"),
                            ("PWA", "Progressive Web App"),
                            ("SDK", "Software Development Kit"),
                            ("RWD", "Responsive Web Design"),
                            ("SQL", "Structured Query Language"),
                            ("IDE", "Integrated Development Environment"),
                        ],
                        default="Admin",
                        max_length=5,
                    ),
                ),
            ],
        ),
    ]
