# Generated by Django 5.0.2 on 2025-11-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('fruit_vegetables', 'Fruit and vegetables'), ('starchy_food', 'Starchy food'), ('dairy', 'Dairy'), ('protein', 'Protein'), ('fat', 'Fat')], default=('fruit_vegetables', 'Fruit and vegetables'), max_length=33)),
            ],
        ),
    ]
