# Generated by Django 5.1.4 on 2024-12-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('car_information', models.CharField(max_length=200)),
                ('from_company', models.CharField(max_length=200)),
                ('to_company', models.CharField(max_length=200)),
                ('who_visit', models.CharField(max_length=200)),
                ('enter_date', models.CharField(max_length=200)),
                ('enter_clock', models.CharField(max_length=200)),
                ('exit_date', models.CharField(max_length=200)),
                ('exit_clock', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
