# Generated by Django 5.1.4 on 2025-01-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tag',
            field=models.ManyToManyField(to='todo.tag'),
        ),
    ]
