# Generated by Django 5.1.4 on 2025-01-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tag',
        ),
    ]
