# Generated by Django 5.2.7 on 2025-10-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoblog', '0004_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoblog.post')),
            ],
        ),
    ]
