# Generated by Django 5.0.2 on 2025-09-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_interface_user_re_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
