# Generated by Django 5.2.1 on 2025-05-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_entry', models.CharField(max_length=255)),
                ('time_of_entry', models.CharField(max_length=255)),
                ('purpose_of_visit', models.TextField()),
                ('rules_form', models.ImageField(blank=True, null=True, upload_to='substractor-rules-form/')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_entry', models.CharField(max_length=255)),
                ('time_of_entry', models.CharField(max_length=255)),
                ('meeting_with', models.CharField(max_length=255)),
                ('purpose_of_visit', models.TextField()),
                ('rules_form', models.ImageField(blank=True, null=True, upload_to='rules_form/')),
            ],
        ),
    ]
