# Generated by Django 5.2.1 on 2025-05-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_control', '0002_category_subcontractor_category_visitor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
