# Generated by Django 5.2.1 on 2025-05-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_control', '0003_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
