# Generated by Django 5.2.1 on 2025-05-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_control', '0004_remove_subcontractor_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
