# Generated by Django 5.2.1 on 2025-05-27 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_control', '0007_visitor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='security_control.category'),
            preserve_default=False,
        ),
    ]
