# Generated by Django 5.2.1 on 2025-05-27 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_control', '0009_alter_visitor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_control.category'),
        ),
    ]
