# Generated by Django 5.2.1 on 2025-05-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_control', '0010_alter_visitor_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
