# Generated by Django 5.1.4 on 2024-12-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
    ]
