# Generated by Django 5.2.1 on 2025-05-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="register_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("confirm_password", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("confirm_email", models.EmailField(max_length=254)),
                (
                    "dept",
                    models.CharField(
                        choices=[
                            ("Admin", "Administrator"),
                            ("PY", "Project Manager"),
                            ("UX", "User Experience"),
                            ("UI", "User Interface"),
                        ],
                        default="UX",
                        max_length=5,
                    ),
                ),
            ],
        ),
    ]
