# Generated by Django 5.2.1 on 2025-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_register_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("avatar", models.ImageField(upload_to="avatar/")),
            ],
        ),
    ]
