# Generated by Django 5.1.6 on 2025-03-03 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XDEVS', '0002_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='XDEVS.category'),
        ),
    ]
