# Generated by Django 5.0.2 on 2025-10-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_favpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavPost',
        ),
    ]
