# Generated by Django 5.0.2 on 2025-10-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0008_delete_favpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.interface_user')),
            ],
        ),
    ]
