# Generated by Django 5.0.2 on 2025-10-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0009_favpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavPost',
        ),
    ]
