# Generated by Django 5.0.2 on 2025-11-01 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoblog', '0006_favpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fotoblog.page'),
            preserve_default=False,
        ),
    ]
