# Generated by Django 5.1.5 on 2025-01-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
