# Generated by Django 5.1.4 on 2024-12-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_category_slug_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='mail_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
