# Generated by Django 5.1.4 on 2024-12-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_mail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='mail_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
