# Generated by Django 5.2 on 2025-05-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="user",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="blog.user"
            ),
            preserve_default=False,
        ),
    ]
