# Generated by Django 5.2 on 2025-05-04 16:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_category_user_profile_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1, editable=False, populate_from="user.username"
            ),
            preserve_default=False,
        ),
    ]
