# Generated by Django 5.2 on 2025-05-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_profile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.profile",
            ),
            preserve_default=False,
        ),
    ]
