# Generated by Django 5.2 on 2025-05-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_category_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
