# Generated by Django 5.2 on 2025-05-04 16:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_profile_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="user__username"
            ),
        ),
    ]
