# Generated by Django 5.2 on 2025-05-04 16:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="get_username_for_slug"
            ),
        ),
    ]
