# Generated by Django 5.1.5 on 2025-01-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_rename_tag_old'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Old',
            new_name='Tag',
        ),
    ]
