# Generated by Django 5.1.7 on 2025-03-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='tag',
            field=models.ManyToManyField(to='pages.tag'),
        ),
    ]
