# Generated by Django 5.0.2 on 2025-11-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotoblog', '0007_post_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='page',
        ),
    ]
