# Generated by Django 5.0.2 on 2025-11-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoblog', '0010_remove_post_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='page_logo/')),
            ],
        ),
    ]
