# Generated by Django 5.1.6 on 2025-03-08 22:01

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XDEVS', '0003_developer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer', to='XDEVS.category'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='XDEVS.category')),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='XDEVS.tag'),
        ),
    ]
