# Generated by Django 5.2 on 2025-04-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_developer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
