# Generated by Django 5.0.2 on 2025-08-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
