# Generated by Django 5.0.2 on 2025-05-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xdevs', '0002_languages_web_pages_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_pages',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
