# Generated by Django 5.0.2 on 2025-05-31 16:27

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xdevs', '0003_remove_web_pages_tag_delete_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='W_Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='web_pages',
            name='tag',
            field=models.ManyToManyField(to='xdevs.w_languages'),
        ),
    ]
