# Generated by Django 5.2.7 on 2025-11-13 00:45

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='random_names',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
