# Generated by Django 5.0.2 on 2025-11-15 21:27

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anon_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('hobbies', models.CharField(choices=[('Table_Tennis', 'Table Tennis'), ('Basketball', 'Basketball'), ('Bowling', 'Bowling'), ('Volleyball', 'Volleyball')], max_length=20)),
                ('skills', models.CharField(choices=[('Web', [('Front_End', 'Javascript React')])], max_length=20)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
    ]
