# Generated by Django 5.0.2 on 2025-11-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopractices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon_user',
            name='data_base',
            field=models.CharField(choices=[('Data Base', 'Sql Postegre_Sql')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anon_user',
            name='skills',
            field=models.CharField(choices=[('Front End', [('js', 'JavaScript'), ('react', 'React')]), ('Back End', [('py', 'Python'), ('dj', 'Django')])], max_length=20),
        ),
    ]
