# Generated by Django 5.1.4 on 2024-12-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todolar_category_todolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='todolar',
        ),
        migrations.DeleteModel(
            name='Todolar',
        ),
    ]
