# Generated by Django 5.1.4 on 2024-12-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_category_todolar_delete_todolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
