# Generated by Django 5.1.4 on 2024-12-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
