# Generated by Django 5.1.5 on 2025-01-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_tag_developers_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Old',
        ),
    ]
