# Generated by Django 5.0.2 on 2025-09-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0022_tag_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='add_tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
