# Generated by Django 5.0.2 on 2025-11-15 16:11

import django.core.validators
import django.db.models.functions.datetime
import djangopractices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonimUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Nickname sadece küçük harf ile oluşmalı ve en fazla 10 karakter uzunluğunda olmalıdır!', regex='^[a-z]{1,10}$')])),
                ('email', models.EmailField(blank=True, default=djangopractices.models.email_generator, max_length=254, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
    ]
