# Generated by Django 5.2.7 on 2025-11-17 20:23

import django.db.models.expressions
import djangopractices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(choices=djangopractices.models.company_generator, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SquareCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField()),
                ('area', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('side'), '*', models.F('side')), output_field=models.BigIntegerField())),
            ],
        ),
    ]
