# Generated by Django 5.2.7 on 2025-11-17 20:28

import djangopractices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopractices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.SmallIntegerField(choices=djangopractices.models.generate_count, db_default=0),
        ),
    ]
