# Generated by Django 5.2.7 on 2025-11-17 20:34

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopractices', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('count'), '*', models.F('price')), output_field=models.DecimalField(decimal_places=2, max_digits=10)),
        ),
    ]
