# Generated by Django 5.2.7 on 2025-11-17 15:44

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquareCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField()),
                ('area', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('side'), '*', models.F('side')), output_field=models.BigIntegerField())),
            ],
        ),
    ]
