# Generated by Django 5.2 on 2025-04-22 10:34

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('dev_img', models.ImageField(upload_to='dev_img/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
