# Generated by Django 5.0.2 on 2025-08-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='weblog.tag'),
        ),
    ]
