# Generated by Django 5.0.2 on 2025-08-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0010_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='weblog.tag'),
        ),
    ]
