# Generated by Django 5.0.2 on 2025-08-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0017_post_add_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='add_tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
