# Generated by Django 5.0.2 on 2025-11-08 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityControl', '0007_remove_taseron_is_outside_yuk_arac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calısan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('tc_kimlik_no', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik Numarası 11 haneli olmalı ve 0 ile başlamamalıdır.', regex='^[1-9][0-9]{10}$')])),
                ('departman', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
