# Generated by Django 5.0.2 on 2025-11-08 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityControl', '0010_alter_calısan_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calısan',
            name='tel',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Lütfen telefon numaranızı başında 0 olmadan girin!', regex='^[1-9][0-9]{9}$')]),
        ),
    ]
