# Generated by Django 5.0.2 on 2025-11-08 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityControl', '0011_alter_calısan_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='havuz_arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=100, unique=True)),
                ('baslangic_km', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message="Km bilgisi 0'dan farklı ve max. 6 haneli olabilir!", regex='^[1-6]\\d{0,5}$')])),
                ('son_km', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message="Km bilgisi 0'dan farklı ve max. 6 haneli olabilir!", regex='^[1-6]\\d{0,5}$')])),
                ('net_km', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('gidecegi_yer', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('is_inside', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
