# Generated by Django 5.0.2 on 2025-11-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityControl', '0012_havuz_arac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='havuz_arac',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='havuz_arac',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='havuz_arac',
            name='cikis_tarihi_saati',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='havuz_arac',
            name='giris_tarihi_saati',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
