# Generated by Django 5.0.2 on 2025-11-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityControl', '0013_remove_havuz_arac_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='havuz_arac',
            name='surucu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securityControl.calısan'),
            preserve_default=False,
        ),
    ]
