# Generated by Django 5.0.2 on 2025-11-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityControl', '0014_havuz_arac_surucu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='havuz_arac',
            old_name='surucu',
            new_name='calisan',
        ),
    ]
