# Generated by Django 5.0.2 on 2025-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityControl', '0015_rename_surucu_havuz_arac_calisan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='havuz_arac',
            name='plaka',
            field=models.CharField(max_length=100),
        ),
    ]
