# Generated by Django 5.0.2 on 2025-08-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favs',
            field=models.BooleanField(default=False),
        ),
    ]
