# Generated by Django 5.0.2 on 2025-08-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0011_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
