# Generated by Django 5.0.2 on 2025-08-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0014_post_addtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='addTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
