# Generated by Django 5.0.2 on 2025-08-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0016_tag_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
