# Generated by Django 5.0.2 on 2025-08-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0020_remove_post_tag_remove_post_add_tag_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
